CREATE TABLE TIPOOLOR (ID INTEGER AUTO_INCREMENT NOT NULL, HEXCOLOR VARCHAR(255), NAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE PUNTOMONITOREO (ID INTEGER AUTO_INCREMENT NOT NULL, LATITUD VARCHAR(255), LONGITUD VARCHAR(255), NAME VARCHAR(255), PRIMARY KEY (ID))
